// File generated by Antigravity using Firebase Console data.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGPE98CY6Vwg06jzwaH77XkCUo_chDYhc',
    appId: '1:883156188597:web:b9a449573cd42cb9e22dfc',
    messagingSenderId: '883156188597',
    projectId: 'trustnepal-ab17e',
    authDomain: 'trustnepal-ab17e.firebaseapp.com',
    storageBucket: 'trustnepal-ab17e.firebasestorage.app',
    measurementId: 'G-EE2J04YVD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGPE98CY6Vwg06jzwaH77XkCUo_chDYhc',
    appId: '1:883156188597:android:0fb8a42d566fa84ee22dfc',
    messagingSenderId: '883156188597',
    projectId: 'trustnepal-ab17e',
    storageBucket: 'trustnepal-ab17e.firebasestorage.app',
  );
}
